### ISSUE TITLE
Coordinate conversion needed

### ISSUE THREAD

**Issue by james-yoo** [nano-roboscan/NSL-3130AA-ROS2#2]
Hi,

It seems that the point cloud is publishing with camera coordinates(z-axis: forward) as follows:
![Screenshot from 2023-02-15 15-26-38](https://user-images.githubusercontent.com/23667624/218951996-a655acd0-b3dc-497a-a8c5-614dfede18b4.png)

However, ROS uses right-handed coordinates as described in [REP-103](https://www.ros.org/reps/rep-0103.html), so it should be converted to the right-handed coordinate(x-axis forward).

**Comment by nano-roboscan** [comment]
이슈 수정되었습니다. 다른 의견이 없다면 1주일 후 close하겠습니다.
