### ISSUE TITLE
Lots of warning messages occur

### ISSUE THREAD

**Issue by james-yoo** [nano-roboscan/NSL-3130AA-ROS2#3]
Hi,
I attached a warning log when compiling the source. 
[warning_log.txt](https://github.com/nano-roboscan/NSL-3130AA-ROS2/files/10750674/warning_log.txt)

**Comment by nano-roboscan** [comment]
이슈 수정되었습니다. 다른 의견이 없다면 1주일 후 close하겠습니다.
