### ISSUE TITLE
Warning message occurred

### ISSUE THREAD

**Issue by james-yoo** [nano-roboscan/NSL-3130AA-ROS2#5]
Hi,
The following variables are not initialized, so the warning messages occurred while compiling.
https://github.com/nano-roboscan/NSL-3130AA-ROS2/blob/7e4d02d15165a577c4e488226ace40396420ddf0/NSL3130_driver/src/roboscan_nsl3130/src/roboscan_publish_node.cpp#L629

**Comment by nano-roboscan** [comment]
이슈 수정 되었습니다. 다른 사항이 없다면 1주일 후 이슈 close하겠습니다.
